package org.example.dataobject;

import java.util.List;

public class alsTab1DO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alstab1.user_id
     *
     * @mbg.generated Thu Dec 02 13:48:17 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alstab1.article_id
     *
     * @mbg.generated Thu Dec 02 13:48:17 CST 2021
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alstab1.rating
     *
     * @mbg.generated Thu Dec 02 13:48:17 CST 2021
     */
    private Double rating;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alstab1.user_id
     *
     * @return the value of alstab1.user_id
     *
     * @mbg.generated Thu Dec 02 13:48:17 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alstab1.user_id
     *
     * @param userId the value for alstab1.user_id
     *
     * @mbg.generated Thu Dec 02 13:48:17 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alstab1.article_id
     *
     * @return the value of alstab1.article_id
     *
     * @mbg.generated Thu Dec 02 13:48:17 CST 2021
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alstab1.article_id
     *
     * @param articleId the value for alstab1.article_id
     *
     * @mbg.generated Thu Dec 02 13:48:17 CST 2021
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alstab1.rating
     *
     * @return the value of alstab1.rating
     *
     * @mbg.generated Thu Dec 02 13:48:17 CST 2021
     */
    public Double getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alstab1.rating
     *
     * @param rating the value for alstab1.rating
     *
     * @mbg.generated Thu Dec 02 13:48:17 CST 2021
     */
    public void setRating(Double rating) {
        this.rating = rating;
    }


}