package org.example.dataobject;

public class StudentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sno
     *
     * @mbg.generated Fri Nov 26 16:58:43 CST 2021
     */
    private String sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sage
     *
     * @mbg.generated Fri Nov 26 16:58:43 CST 2021
     */
    private Integer sage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sno
     *
     * @return the value of student.Sno
     *
     * @mbg.generated Fri Nov 26 16:58:43 CST 2021
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sno
     *
     * @param sno the value for student.Sno
     *
     * @mbg.generated Fri Nov 26 16:58:43 CST 2021
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sage
     *
     * @return the value of student.Sage
     *
     * @mbg.generated Fri Nov 26 16:58:43 CST 2021
     */
    public Integer getSage() {
        return sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sage
     *
     * @param sage the value for student.Sage
     *
     * @mbg.generated Fri Nov 26 16:58:43 CST 2021
     */
    public void setSage(Integer sage) {
        this.sage = sage;
    }
}