package org.example.service.model;

public class alsTab1Model {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alstab1.user_id
     *
     * @mbg.generated Thu Dec 02 12:24:14 CST 2021
     */
    private Integer userId;

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getArticleId() {
        return articleId;
    }

    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    public Double getRating() {
        return rating;
    }

    public void setRating(Double rating) {
        this.rating = rating;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alstab1.article_id
     *
     * @mbg.generated Thu Dec 02 12:24:14 CST 2021
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alstab1.rating
     *
     * @mbg.generated Thu Dec 02 12:24:14 CST 2021
     */
    private Double rating;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alstab1.user_id
     *
     * @return the value of alstab1.user_id
     *
     * @mbg.generated Thu Dec 02 12:24:14 CST 2021
     */
}
